### PR TITLE
extra examples

### PR DESCRIPTION
**Pull request by npisanti**
binary logic
random distribution

### CODE REVIEW

**Comment by cancel** [comment]
Looks fine to me

**Comment by neauoire** [comment]
screen shot 2019-01-16 at 7 42 45 am

I've updated the example to follow the `41x17` size, and formatting, of the examples.
Could you double check it's alright?

**Comment by npisanti** [comment]
the comment in the bottom right should be ! OR  (or NOT OR)  instaead of OR

**Comment by neauoire** [comment]
Yeah, about that. So in OrcaJS, it's no longer part of the specs.
So the `!` characters is not allowed. I was wondering if there wasn't another name for it? 
I was thinking maybe I should give **OR** a `R01` too?

screen shot 2019-01-16 at 8 20 59 am

**Comment by npisanti** [comment]
i think it is better without the R01, the input of the boolean operation are the A inputs, and then i made the inputs gradually more complex, the NOR was in the end just to remember you can actually invert the bit of the T mask and get the output with NOT

**Pull request merged**
